# Generated by Django 4.1.2 on 2022-10-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientesAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_discapacidad', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_civil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_estado_civil', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etnia', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_rh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_grupo_rh', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_educativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_nivel_educativo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sexo', models.CharField(max_length=20)),
            ],
        ),
    ]
