# Generated by Django 4.1.2 on 2022-10-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientesAPP', '0002_discapacidad_estado_civil_etnia_grupo_rh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discapacidad',
            name='nom_discapacidad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estado_civil',
            name='nom_estado_civil',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='nom_etnia',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='nivel_educativo',
            name='nom_nivel_educativo',
            field=models.CharField(max_length=50),
        ),
    ]
