# Generated by Django 4.1.2 on 2022-10-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientesAPP', '0003_alter_discapacidad_nom_discapacidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pacientesAPP.tipo_identificacion')),
            ],
        ),
    ]
