# Generated by Django 4.1.2 on 2022-10-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientesAPP', '0005_paciente_direccion_paciente_discapacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
