# Generated by Django 4.1.2 on 2022-10-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientesAPP', '0008_departamento_municipio_paciente_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='cod_departamento',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cod_municipio',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
